lib/algolia/webmock.rb, spec/mock_spec.rb
For some reason this stub:
```ruby 
WebMock.stub_request(:get, /.*\.algolia\.(io|net)\/1\/indexes\/[^\/]+/).to_return(:body => '{}')
``` 
caused the following error:
```console
NoMethodError:
undefined method `map' for nil:NilClass
```
in this spec:
```ruby
require "rails_helper"
describe "With a mocked client" do
it "shouldn't perform any API calls here" do
create(:group) 
expect(Group.search("")).to be_empty
end
end
```
The error was thrown because `algoliasearch-rails` expects having some keys like `hits` and `page` in the JSON response and fails if response doesn't have them.
I'm not sure if we should have such verbose stub in `algoliasearch-client-ruby`, probably it is better to add empty response handling to `algoliasearch-rails`, but this PR can work as a short-term fix. What do …
=> Fix broken request stub

README.md
When testing `Algolia#search`, the response is different from what the docs suggest.
_(trailing whitespace trimmed as a side effect)_
=> Update Algolia#search mocked response

.travis.yml
Hi,
I'm a Customer Support Specialist at Travis CI.
Here's a small change (following a discussion with @ElPicador) that should help you get faster builds. Here are some explanation on what it does:
1) Removing the `install:` section will make Travis CI call `bundle install` under the hood. Dependencies will be installed in a default directory compatible with [our caching feature](https://docs.travis-ci.com/user/caching/).
2) `cache: bundler` tells Travis CI to cache your Bundler dependencies. Hence, they will be zipped at the end of a build and uploaded to S3. Afterward, they will be downloaded and extracted at the start of a new build. The cache archive is updated anytime your dependencies change.
Hope this helps. Don't hesitate to reach out at contact [at] travis-ci [dot] com if you …
=> Cache Bundler dependencies on Travis CI

lib/algolia/client.rb
I'm not entirely sure if I got it all wrong, or if those weren't removed when it was supposed to be, can you confirm I'm not doing nonsense @redox ?
=> fix(client): client methods should be client-scoped

algoliasearch.gemspec
The current dependency on httpclient, `"~> 2.8.2.4"` prevents upgrades to `2.8.3`, the latest version of this gem.  A previous version of this dependency was `"~>2.8.2"`, which allowed the 2.8.3 upgrade.  Revert to a less-specific dependency to allow for upgrades.
Please let me know if there's more information I can provide!  Thank you for a fantastic tool!
=> Update httpclient dependency

lib/algolia/client.rb, lib/algolia/index.rb, spec/client_spec.rb, spec/mock_spec.rb
@redox, would love your eyes on this one. I'm not entirely sure how we handled method renaming in the past.
=> chore(naming): rename user_key methods to api_keys

lib/algolia/index.rb, spec/client_spec.rb
After looking through the source of this library I realized that there wasn't a way to just check the status of a task instead of waiting for a task to finish. So I decided to create a pull request in the hopes that you guys would merge it and add this functionality. I could really use it.
=> Add get_task_status method to Algolia::Index class.

lib/algolia/webmock.rb
I'm currently having the error below and realized that there's something missing in the stubs' return JSON payload. With the changes the error was eliminated.
```
NoMethodError:
undefined method `*' for nil:NilClass
```
=> Fix missing 'nbHits' and 'nbPages' JSON objects in the webmock file

lib/algolia/index.rb, lib/algolia/webmock.rb, spec/mock_spec.rb
=> Improved delete_by_query to not run the wait_task if not appropriate

lib/algolia/webmock.rb, spec/mock_spec.rb, spec/spec_helper.rb
This is needed because when you require algolia/webmock, the mocks will
work only in one spec at rspec, if you required webmock/rspec.
This happens because webmock/rspec will clear all stubs between examples
and we need to stub again for the next one.
The new approach is:
require 'algolia/webmock'
RSpec.configure do |config|
config.before(:each) { Algolia::WebMock.mock! }
end
Fixes #223 
Fixes #100
=> Allow to reuse the algolia webmocks

lib/algolia/client.rb, lib/algolia/protocol.rb, spec/client_spec.rb
Closes https://github.com/algolia/algoliasearch-client-ruby/issues/241
=> Fix get_logs always returning type `all`

lib/algolia/client.rb
Transparent gzip decompression in not compatible with httplog gem.
Fix https://github.com/algolia/algoliasearch-rails/issues/273
=> Make HttpClient transparent_gzip_decompression configurable

lib/algoliasearch.rb
With these statements, the AlgoliaSearch family of gems breaks our application on CI, as both the Gem and our host app require and initialize Bundler. 
Since upgrading to Bundler 1.16, starting our app on CI fails with
``` 
Bundler::GemRequireError: There was an error while trying to load the gem 'algoliasearch-rails'.
Gem Load Error is: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
Backtrace for gem load error is:
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/errors.rb:9:in `status_code'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/errors.rb:20:in `<module:Bundler>' …
```
=> Do not setup Bundle or RubyGems

Gemfile, algoliasearch.gemspec
Attempt to fix hardcoded dependency due to `hashdiff` wrong dependency declaration (https://github.com/algolia/algoliasearch-client-ruby/pull/257/files/36bcd0b1c4d05776dcbdb362c15a609c81f41cde)
=> Fix `hashdiff` wrong dependency

.travis.yml, spec/client_spec.rb
Enable community PR's
Read more: https://blog.algolia.com/travis-encrypted-variables-external-contributions/
=> Build community PR

lib/algolia/index.rb, spec/client_spec.rb
First time for years I'm writing Ruby. Absolutely any comment is more than welcome.
=> fix: Prevent saving a rule with an empty objectID

lib/algolia/client.rb, lib/algolia/index.rb, lib/algolia/protocol.rb
https://github.com/algolia/algoliasearch-client-ruby/issues/269 PR that went under the radar cc @julienbourdeau
=> API review

spec/client_spec.rb
Remove the following warning:
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<Algolia::AlgoliaProtocolError: 403: Cannot GET to https://K7MLRQH1JG-dsn.algolia.net/1/indexes: {"message":"Invalid Application-ID or API key","status":403}
(403)>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/julien/Algolia/API-clients/ruby/spec/client_spec.rb:1124:in …
```
=> fix(tests): Fix warning for unspecified exception

lib/algolia/index.rb
Cursor can get very long and exceed the max url size, for that reason
we always pass it in the body of the request.
=> fix(browse): Ensure cursor is passed in the body

lib/algolia/client.rb, lib/algolia/protocol.rb, spec/client_mcm_spec.rb
Related PR:
* C#: https://github.com/algolia/algoliasearch-client-csharp/pull/495
* PHP: https://github.com/algolia/algoliasearch-client-php/pull/331
* Python: https://github.com/algolia/algoliasearch-client-python/pull/302
Doc snippets are coming
=> Introduce Multi Cluster Management

CHANGELOG.md, Rakefile
When the rake task is started, the current / old version is loaded and needs to be reloaded.
=> Fix release task

lib/algolia/client.rb, lib/algolia/index.rb
| New feature?      | yes    
| Need Doc update   | yes (not sure)
2 methods about taskID initially available in the `Index` moved to the `Client`. The original methods on the index still work and are **not** deprecated.
```ruby
client.wait_task(index_name, taskID, time_before_retry, requestHeaders)
client.get_task_status(index_name, taskID, requestHeaders)
index.wait_task(taskID)
index.get_task_status(taskID, requestHeaders)
```
You could get some taskID from the engine without necessarily have an instance of Index. Instead of instanciating an index that you won't need, you can now call `waitTask` and `getTaskStatus` on the client.
* In the ruby client, bang methods (like …
=> Expose waitTask in the client

spec/client_mcm_spec.rb, spec/spec_helper.rb
I introduce a new helper functions in test called `auto_retry`. Some operations are asynchronous but the engine doesn't return a taskID. This function execute a block and retry multiple times before failing.
For MCM, if a userID wasn't assigned before we try to retrieve or delete, it would fail. With `auto_retry` we wait a few seconds and try agian before failing.
Another thing, when you search for a userID, you might not find the one you want because there is one with a close name ranked higher. I fixed that by using a unique userID for every build.
New MCM tests were making the build very unstable.
=> Tests: make MCM tests more stable

lib/algolia/client.rb, spec/client_spec.rb, spec/stub_spec.rb
We'd like to add the language version to each client. Today everything is overridden if you pass a user-agent value to the constructor of the Client class. 
I'd rather leave the client and language version and let users add something specific at the end.
Any comment is welcome.
Pull request on Rails is coming.
=> UserAgent: Add ruby version

Rakefile
the `prepend` method is an alias to `unshift` but was introduced in Ruby 2.5. In order to keep the script working with older version of ruby, we move back to unshift.
=> Rake: use unshift to keep compat with older ruby versions

lib/algolia/client.rb, spec/client_spec.rb
This Pull Request adds the methods `copy_settings`, `copy_synonyms` and `copy_rules` into the `Client::class`. Behind the scenes, every new copy method is just performing a `copy_index` with a different `scope` param, example:
```ruby
def copy_rules(src_index, dst_index, request_options = {})
copy_index(src_index, dst_index, ['rules'], request_options)
end
```
=> Feat(scoped-copy-methods): Adds copy_settings, copy_synonyms and copy_rules

lib/algolia/index.rb, spec/client_spec.rb
This Pull Request adds the methods `replace_all_objects`, `replace_all_rules` and `replace_all_synonyms` into the `Index::class`.
=> Feat(replace-all-methods): Adds replace_all_objects, replace_all_rules and replace_all_synonyms

lib/algolia/protocol.rb
| Related Issue     | Fix #329
Fix #239
If you use a number as an objectID for your Synonyms and Rules, you have to convert them to a string yourself (when the ID is used in a url route). We now call `to_s` for your.
=> Ensure objectID is a string before escaping

algoliasearch.gemspec
| Related Issue     | Fix #330
Make sure `insights` is part of the gemspec
Users currently importing the lib have an error because a file is missing from the release
@julienbourdeau you'll still need to do a RubyGems release after merging
=> Add insights.rb to gemspec

lib/algolia/client.rb, lib/algolia/protocol.rb, spec/client_spec.rb
| New feature?      | yes    
Algolia API introduced a new endpoint to restore a deleted API key 🎉 
```ruby
Algolia.restore_api_key(the_deleted_key, request_options)
```
=> Add restore_api_key method

README.md
This pull request fixes the link of the badge within the readme.
=> chore: updates readme badges link

algoliasearch.gemspec
Block json dependencie for older Ruby version as json 2.3.0 is out and is not compatible with Ruby <= 1.9.3
=> chore(gemspec): block json dep for older ruby versions

.circleci/config.yml, Rakefile, lib/algolia/helpers.rb, lib/algolia/responses/add_api_key_response.rb, lib/algolia/responses/delete_api_key_response.rb, lib/algolia/responses/restore_api_key_response.rb, lib/algolia/responses/update_api_key_response.rb, lib/algolia/search_index.rb, test/algolia/integration/recommendation_client_test.rb, test/algolia/integration/search_index_test.rb, test/algolia/unit/helpers_test.rb
| Related Issue     | Fix #407 
This PR introduces the use of lambda's in the `find_object` method instead of using blocks.
=> feat(find_objects): use lambda instead of block

lib/algolia/account_client.rb, spec/account_client_spec.rb
| Related Issue     | Fix #398
There was a bug preventing the fetching of all the objects from the source index. Instead, it retrieved only the first 1000 as it's the default number of hits per page. This commit fixes it
=> fix(account-client): retrieve all objects from source index

lib/algolia/config/algolia_config.rb, lib/algolia/transport/transport.rb, sig/config/algolia_config.rbs
Rename `default_headers` to `headers`
=> fix(config): changes default_headers to headers

lib/algolia/analytics_client.rb, lib/algolia/config/analytics_config.rb, lib/algolia/config/base_config.rb, lib/algolia/config/insights_config.rb, lib/algolia/config/recommendation_config.rb, lib/algolia/config/search_config.rb, lib/algolia/insights_client.rb, lib/algolia/recommendation_client.rb, lib/algolia/search_client.rb, test/algolia/unit/retry_strategy_test.rb, test/test_helper.rb, upgrade_guide.md
Renames `app_id` to `application_id` to smooth the upgrading and avoid BC breaks on Rails integration
=> fix(config): rename app_id to application_id

.rubocop.yml, lib/algolia/search_index.rb, test/algolia/integration/analytics_client_test.rb, test/algolia/integration/insights_client_test.rb, test/algolia/integration/search_client_test.rb
Rename `index_name` in the `Index` class as it is redundant and reduce upgrade on the Rails side
=> chore(index): renames index_name to name

lib/algolia/index.rb
The `hitsPerPage` param had a typo, preventing the rule browser from retrieving all the rules. It's been fixed
=> fix(rules): export rules hitsPerPage

algolia.gemspec
| BC breaks?        | no   
| Related Issue     | Fix #431 
Updates the dependency range of `faraday` gem to allow versions > 1.0
=> chore: update faraday dependency range

lib/algolia/search_client.rb
| New feature?      |no
| Related Issue     | None
Using `strip` instead of `strip!` in `init_index`.
Currently calling `init_index` with a frozen string causes a `FrozenError` as the method tries to mutate `index_name`. Using `strip` instead of `strip!` gives the same value without mutation.
=> Don't mutate index name when stripping

CHANGELOG.md, lib/algolia/search_client.rb, test/algolia/integration/search_client_test.rb
The request options were not send in the waitable version of `app_api_key`
=> fix(api-keys): send opts with waitable method

.circleci/config.yml
Adds a call to the API key dealer to run external contributors' PRs
=> chore: update CI credentials for external contributors

lib/algolia/search_index.rb, test/algolia/integration/search_index_test.rb
| Related Issue     | Fix #450
| Need Doc update   | yes/no
The parameter `forwardToReplicas` should be handled independently in the `set_settings` method
=> fix(set-settings): forwardToReplicas param

lib/algolia/http/http_requester.rb
Before this change a read-only host could get memoized preventing writes in subsequent requests.
Closes #454
| Related Issue     | Fix #454 
Before this change the first used host would get memoized. If this was a read-only host, then future requests would also use this read-only host. Even if this requests would require a write host.
This PR fixes that bug. The existing code comments already referred to a `@connections` variable. So I think this solution might have been implemented before, but got removed for some reason.
I couldn't get the test suite to run, so I suggest doing that before merging this PR. I also suggest adding …
=> fix: Memoize host based on accept attribute

lib/algolia/search_client.rb
This adds `search` as an alias for the `multiple_queries` method to align method names across all API clients.
=>  chore: add `search` alias for multiple queries

.circleci/config.yml, test/algolia/integration/search_client_test.rb
| BC breaks?        | no (?)
| Need Doc update   | yes/no
This PR is meant to add support for version 3 of Ruby, which was released on 25 December 2020.
The following dependencies don't support Ruby v3 yet, meaning we can't upgrade for now:
- [`net-http-persistent`](https://github.com/drbrain/net-http-persistent/) (https://github.com/drbrain/net-http-persistent/issues/123)
=> feat: add support for Ruby v3

test/algolia/integration/mocks/mock_requester.rb
This adds the `status` field to the response provided by the `MockRequester`. This prevents an infinite loop while using the `MockRequester` to perform a `wait_task`.
=> fix: add status field to `MockRequester` response

lib/algolia/search_client.rb, test/algolia/integration/search_client_test.rb
| Related Issue     | Fix #462 
This updates the client to accept a hash for `params` when performing a `multiple_queries`, rather than only accepting a string.
=> fix: allow hash in multiple queries

README.md, lib/algolia/responses/add_api_key_response.rb, lib/algolia/responses/delete_api_key_response.rb, lib/algolia/responses/restore_api_key_response.rb, lib/algolia/responses/update_api_key_response.rb, lib/algolia/search_index.rb
| Related Issue     | -
There are some `sleep` with `Defaults::WAIT_TASK_DEFAULT_TIME_BEFORE_RETRY / 1000` and the constant variable is `100` as 100 milliseconds.
However, `100 / 1000` is `0` calculated as Integer.
So, I fix it to `100.to_f / 1000` for 100 msec sleeping.
The changes in `lib/algolia/responses/*.rb` are not so important because these are irregular error handling logic and sleep time is increased by retry count.
On the other hand, `lib/algolia/search_index.rb` is important.
It's normal logic that occurs frequently.
Ref. I found out similar logic [here](https://github.com/algolia/algoliasearch-client-ruby/blob/052e96 …
=> fix: API polling flood issue due to msec sleep time mishandling

lib/algolia/search_index.rb, test/algolia/integration/search_index_test.rb, test/test_helper.rb
| Related Issue     | -
When the `get_settings` method is called in [algoliasearch-rails gem](https://github.com/algolia/algoliasearch-rails/blob/2358e3ca6e3b2242a345b3e2d360e2099fbbc9d6/lib/algoliasearch-rails.rb#L796) with argument `(:getVersion => 1)`, the client send HTTP GET to `/1/indexes/%s/settings?getVersion=2?getVersion=1`
`?getVersion=2?getVersion=1` is invalid params and the API returns the JSON response contain `"version"=>18446744073709551615`.
This PR fix the HTTP GET target URL with some opts.
- When you use `get_settings` method with some opts you may don't get a correct response.
- algoliasearch-rails gem …
=> fix: API endpoint URL mishandling in get_settings method

lib/algolia/analytics_client.rb, lib/algolia/insights_client.rb, lib/algolia/logger_helper.rb, lib/algolia/personalization_client.rb, lib/algolia/recommend_client.rb, lib/algolia/search_client.rb
| Related Issue     | Fix #434
When you use this gem, your program generate `debug.log` in the working directory. ( ref. #434 )
If you set `ALGOLIA_DEBUG` environment and want to get some algolia gem logging to debug your program, this file is very useful.
However, in almost all situations `debug.log` is a seed of confusion, especially if you are just a program's user that uses this gem.
For general program users, they can't decide why the file is generated because the file is always empty.
Or for program developers who have .gitignore that doesn't contain the line `debug.log`, they might think it's annoying a little.
I …
=> fix: #434: confusing empty debug.log generation in gem users root

lib/algolia/search_client.rb, lib/algolia/search_index.rb
| Related Issue     | n/a
| Need Doc update   | ?
This change adds an optional parameter when constructing an index for the `logger` and allows that to be passed in to the temporary client. This change also ensures that any `Index` built through the `SearchClient#init_index` call gets the logger configured on the client. This will ensure logging is done in a consistent manner across clients instantiated by the library.
The `replace_all_objects` method creates a temporary client which does not have the some configuration as one constructed by users of the library. This leads to inconsistent behaviour when a custom `LoggerHelper` is configured and passed …
=> Pass user configured logger to temp client in `replace_all_objects`

lib/algolia/search_index.rb
This ensures we _always_ remove `createIfNotExists` from our request options. Currently, if you pass it as `false`, [this check](https://github.com/algolia/algoliasearch-client-ruby/pull/458/files#diff-d9ee2258a9e0d0149752df99fc31eb433f3c62cb36d2966b72198cdc924ced43R302) fails. Because of that, we're trying to send a `partialUpdateObjectNoCreate` operation, which doesn't accept the `createIfNotExists` parameter, even if it's `false`. By removing the parameter from our request options we prevent this from happening.
=> fix: always remove createIfNotExists from request options

.circleci/config.yml, README.md, algolia.gemspec, lib/algolia/transport/transport.rb
This PR drops support for older Ruby versions, which are EOL for a while and are currently blocking a dependency upgrade.
=> chore: drop support for older Ruby versions

lib/algolia/transport/transport.rb
| Related Issue     | Fix #484
This PR fixes the issue described in #484, for projects that have Faraday `<1` as a dependency
=> fix: add check for Faraday version

lib/algolia/transport/transport.rb
| Related Issue     |  https://github.com/algolia/algoliasearch-client-ruby/issues/494
Adds the timeout to the request object so we can pass it to the `http_requester`
We can see from here our intention is to end up with the `timeout` and `connect_timeout` keys present in the request object that is later passed to `send_request`
https://github.com/algolia/algoliasearch-client-ruby/blob/c8c8c6b79d34e4788daeb04e1003695c010c87d6/lib/algolia/transport/transport.rb#L51-L69
But in fact we are not actually adding those keys in the `build_request` method
https://github.com/algolia/algoliasearch-client-ruby/blob/c8c8c6b79d34e4788daeb0 …
=> Fix issue with timeout's not being passed to the http_request

lib/algolia/http/http_requester.rb, test/algolia/unit/http_requester_test.rb
| BC breaks?        | ?     
| Related Issue     | N/A
Use the `host.url`, which should be unique, instead of the `host.accept` value, which in most cases is not unique, when caching the http client in the `@connections` instance variable of `http_requester`
Failing to do that, all hosts will actually use the same http client as the first one (assuming they share the same `accept` value). This prevents the retry strategy from working properly
For example:
1. you have `host1`, `host2` & `host3` configured. `host1` is down.
2. you call `algolia_client.indexes`
3. `transporter` -> `retry_strategy` -> `http_requester` will try to request host1 and instantiate an …
=> fix(http_requester): use host url as connections cache key

lib/algolia/helpers.rb, test/algolia/unit/helpers_test.rb
| New feature?      | no 
| BC breaks?        | Technically yes     
| Related Issue     | Reported internally
Change how the index name is encoded in the url by not using `CGI.unescape` first.
Currently, the client doesn't handle index names with `+` signs in their names for example
```rb
index_name = 'foo+ bar'
CGI.unescape(index_name) == 'foo  bar'
CGI.escape(CGI.unescape('foo+ bar')) == 'foo++bar'
```
While the behaviour is more correct and matches what is done in [the js client](https://github.com/algolia/algoliasearch-client-javascript/blob/db9953ce626dc734f8e7eaf88b78d9c9c0bb5a54/packages/client-common/src/helpers.ts#L42-L47) for example, it could break code that relied on …
=> fix(helpers): encode index_name properly
