lib/algolia/webmock.rb

update webmock domain name

---

lib/algolia/index.rb
lib/algolia/protocol.rb
spec/client_spec.rb

Adds the `search_facet` method to the index object.

feat(index): add search_facet

---

lib/algolia/index.rb
spec/client_spec.rb
spec/mock_spec.rb

Add also a delete_by_query! waiting for the last task.
Also set distinct to false.
Fix #221

Fine-tune the delete_by_query making it not wait_task by default.

---

lib/algoliasearch.rb

Due to recent changes https://github.com/algolia/algoliasearch-client-ruby/pull/254/files

Fix missing requirement

---

lib/algolia/client.rb
lib/algolia/index.rb
spec/client_spec.rb

Should be good now!
Please let's not write the associated tests for every method.

feat(request_options): add request options to any method using API calls

---

algoliasearch.gemspec

Simple refactor mainly adding metadata for [RubyGems](https://rubygems.org/gems/algoliasearch)

Add gemspec metadata

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
MAINTAINERS.md

Update common files

---

algoliasearch.gemspec

See https://github.com/algolia/algoliasearch-client-ruby/pull/293

Rename LICENSE file

---

README.md
lib/algolia/client.rb
spec/client_spec.rb

Fix(syntax): this isn't PHP

---

lib/algolia/account_client.rb
lib/algoliasearch.rb
spec/account_client_spec.rb
spec/spec_helper.rb

This Pull Request adds the class `account_client` with a `copy_index` for cross-app index copies.

Feat(adds-account-client-copy-index): Adds account client copy index

---

lib/algolia/client.rb
spec/client_spec.rb

Add multiple_get_objects - fix #316

---

lib/algolia/client.rb
lib/algolia/insights.rb
lib/algolia/protocol.rb
lib/algoliasearch.rb
spec/insights_spec.rb

Introduce Personalization and Insights client
```ruby
client.set_strategy({...})
strategy = client.get_strategy()
```
```ruby
@insights = Algolia::Insights.new({
:application_id => ENV['ALGOLIA_APP_ID']
:api_key => ENV['ALGOLIA_API_KEY']
})
user_insights = @insights.user(user_token)
user_insights.clicked_filters("eventName", "indexName", filters);
user_insights.clicked_object_ids("eventName", "indexName", objectIDs);
user_insights.clicked_object_ids_after_search("eventName", "indexName", objectIDs, positions, "queryID");
user_insights.converted_filters("eventName", "indexName", filters);
user_insights.converted_object_ids("eventName", "indexName", objectIDs);
user_insights.converted_object_idsafter_search("eventName", "indexName", objectIDs, "queryID"); …
```

Introduce Insights and Personalization feature

---

spec/analytics_spec.rb

AA Tests are AB Test but based on the same index, only adding search parameters. It works out of the box but we make sure it works with an integration test.

Add AA Test feature tests

---

.travis.yml
spec/client_mcm_spec.rb

fix(mcm-tests): update tests to make them pass

---

lib/algolia/index.rb
spec/client_spec.rb

| Related Issue     | Fix #351 

Add exists method

---

lib/algolia/client.rb
lib/algolia/error.rb
spec/client_spec.rb

| Related Issue     | Fix #357

feat: remaining validity

---

lib/algolia/index.rb
spec/client_spec.rb

| Related Issue     | Fix #363

fix(exists-method): fix method syntax with an alias

---

test/algolia/integration/search_index_test.rb

| Related Issue     | Fix #392 
This pull request updates the CTS in the ruby client v2 concerning the support of multiple conditions on query rules.

tests(multiple-conditions-rules): updates cts

---

sig/helpers.rbs
sig/iterators/base_iterator.rbs
sig/iterators/object_iterator.rbs
sig/iterators/paginator_iterator.rbs
sig/iterators/rule_iterator.rbs
sig/iterators/synonym_iterator.rbs

Adds typing of the iterators folder + Helpers class

feat(steep): add iterators

---

lib/algolia/version.rb

Change the version in the class

feat(v2): updates version

---

algolia.gemspec
lib/algolia/version.rb

fix(v2): updates gemspec file

---

lib/algolia/defaults.rb

fix(timeouts): revert read and write timeouts

---

test/algolia/integration/search_client_test.rb

| Related Issue     | Fix #395

chore(tests): update restore api key test

---

Gemfile

fix(dependencies): fix ruby 2.2 dependencies

---

upgrade_guide.md

fix(upgrade-guide): code snippets

---

.rubocop.yml
lib/algolia/config/base_config.rb
sig/config/algolia_config.rbs
test/algolia/unit/algolia_config_test.rb
upgrade_guide.md

feat(config): add set_extra_header method

---

lib/algolia/helpers.rb
test/algolia/unit/helpers_test.rb

Fixes the serialising of settings

fix(helpers): deserialize_settings function

---

README.md

chore(docker): updates readme

---

CONTRIBUTING.MD
README.md

Updates the contributing guide

chore: contributing guide

---

algolia.gemspec
lib/algolia/transport/transport.rb

Update Faraday dependency.
Strong dependency on "old" Faraday major.

chore: update faraday dependency range
